class TeslaService
  # https://github.com/teslamotors/fleet-telemetry/blob/main/protos/vehicle_data.proto
  def self.fields(interval)
    {
      VehicleName:                               1.second,
      ChargeState:                               1.second,
      VehicleSpeed:                              1.minute,
      Odometer:                                  30.minutes,
      Location:                                  1.minute,
      GpsState:                                  1.minute,
      GpsHeading:                                1.minute,
      DoorState:                                 1.minute,
      Locked:                                    1.minute,
      FdWindow:                                  30.seconds,
      FpWindow:                                  30.seconds,
      RdWindow:                                  30.seconds,
      RpWindow:                                  30.seconds,
      TpmsPressureFl:                            1.hour,
      TpmsPressureFr:                            1.hour,
      TpmsPressureRl:                            1.hour,
      TpmsPressureRr:                            1.hour,
      InsideTemp:                                30.minutes,
      OutsideTemp:                               30.minutes,
      # ChargeState:                               1.second,
      # VehicleSpeed:                              1.minute,
      # Odometer:                                  30.minutes,
      # # PedalPosition:                             30.minutes,
      # # BrakePedal:                                30.minutes,
      # Location:                                  1.minute,
      # GpsState:                                  1.minute,
      # GpsHeading:                                1.minute,
      # # DCChargingEnergyIn:                        30.minutes,
      # # DCChargingPower:                           30.minutes,
      # # ACChargingEnergyIn:                        30.minutes,
      # # ACChargingPower:                           30.minutes,
      # # ChargeLimitSoc:                            30.minutes,
      # # FastChargerPresent:                        30.minutes,
      # EstBatteryRange:                           30.minutes,
      # # IdealBatteryRange:                         30.minutes,
      # BatteryLevel:                              1.minute,
      # TimeToFullCharge:                          1.minute,
      # ScheduledChargingStartTime:                30.minutes,
      # ScheduledChargingPending:                  30.minutes,
      # ScheduledDepartureTime:                    30.minutes,
      # PreconditioningEnabled:                    30.minutes,
      # # ScheduledChargingMode:                     30.minutes,
      # # ChargeAmps:                                30.minutes,
      # # ChargeEnableRequest:                       30.minutes,
      # # ChargerPhases:                             30.minutes,
      # # ChargePortColdWeatherMode:                 30.minutes,
      # # ChargeCurrentRequest:                      30.minutes,
      # # ChargeCurrentRequestMax:                   30.minutes,
      # # BatteryHeaterOn:                           30.minutes,
      # # NotEnoughPowerToHeat:                      30.minutes,
      # # SuperchargerSessionTripPlanner:            30.minutes,
      # DoorState:                                 1.minute,
      # Locked:                                    1.minute,
      # FdWindow:                                  1.minute,
      # FpWindow:                                  1.minute,
      # RdWindow:                                  1.minute,
      # RpWindow:                                  1.minute,
      # VehicleName:                               30.minutes,
      # # SentryMode:                                30.minutes,
      # # SpeedLimitMode:                            30.minutes,
      # # CurrentLimitMph:                           30.minutes,
      # Version:                                   30.minutes,
      # TpmsPressureFl:                            30.minutes,
      # TpmsPressureFr:                            30.minutes,
      # TpmsPressureRl:                            30.minutes,
      # TpmsPressureRr:                            30.minutes,
      # # TpmsLastSeenPressureTimeFl:                30.minutes,
      # # TpmsLastSeenPressureTimeFr:                30.minutes,
      # # TpmsLastSeenPressureTimeRl:                30.minutes,
      # # TpmsLastSeenPressureTimeRr:                30.minutes,
      # InsideTemp:                                30.minutes,
      # OutsideTemp:                               30.minutes,
      # # SeatHeaterLeft:                            30.minutes,
      # # SeatHeaterRight:                           30.minutes,
      # # SeatHeaterRearLeft:                        30.minutes,
      # # SeatHeaterRearRight:                       30.minutes,
      # # SeatHeaterRearCenter:                      30.minutes,
      # # AutoSeatClimateLeft:                       30.minutes,
      # # AutoSeatClimateRight:                      30.minutes,
      # # DriverSeatBelt:                            30.minutes,
      # # PassengerSeatBelt:                         30.minutes,
      # # DriverSeatOccupied:                        30.minutes,
      # # LateralAcceleration:                       30.minutes,
      # # LongitudinalAcceleration:                  30.minutes,
      # # CruiseSetSpeed:                            30.minutes,
      # # LifetimeEnergyUsed:                        30.minutes,
      # # LifetimeEnergyUsedDrive:                   30.minutes,
      # # BrakePedalPos:                             30.minutes,
      # RouteLastUpdated:                          1.minute,
      # RouteLine:                                 1.minute,
      # MilesToArrival:                            1.minute,
      # MinutesToArrival:                          1.minute,
      # OriginLocation:                            1.minute,
      # DestinationLocation:                       1.minute,
      # CarType:                                   30.minutes,
      # Trim:                                      30.minutes,
      # ExteriorColor:                             30.minutes,
      # RoofColor:                                 30.minutes,
      # ChargePort:                                30.minutes,
      # ChargePortLatch:                           30.minutes,
      # PairedPhoneKeyAndKeyFobQty:                30.minutes,
      # CruiseFollowDistance:                      30.minutes,
      # EnergyRemaining:                           1.minute,
      # ServiceMode:                               30.minutes,
      # DestinationName:                           1.minute,
      # DetailedChargeState:                       30.minutes,
      # ChargePortDoorOpen:                        1.minute,
      # # ChargerVoltage:                            30.minutes,
      # # ChargingCableType:                         30.minutes,
      # ClimateKeeperMode:                         1.minute,
      # DefrostForPreconditioning:                 30.minutes,
      # DefrostMode:                               30.minutes,
      # # EfficiencyPackage:                         30.minutes,
      # # EstimatedHoursToChargeTermination:         30.minutes,
      # # ExpectedEnergyPercentAtTripArrival:        30.minutes,
      # # HvacACEnabled:                             30.minutes,
      # # HvacAutoMode:                              30.minutes,
      # # HvacFanSpeed:                              30.minutes,
      # # HvacFanStatus:                             30.minutes,
      # # HvacLeftTemperatureRequest:                30.minutes,
      # # HvacPower:                                 30.minutes,
      # # HvacRightTemperatureRequest:               30.minutes,
      # # HvacSteeringWheelHeatAuto:                 30.minutes,
      # # HvacSteeringWheelHeatLevel:                30.minutes,
      # # RearDisplayHvacEnabled:                    30.minutes,
      # RearSeatHeaters:                           30.minutes,
      # RemoteStartEnabled:                        30.minutes,
      # RouteTrafficMinutesDelay:                  30.minutes,
      # SoftwareUpdateDownloadPercentComplete:     1.minute,
      # SoftwareUpdateExpectedDurationMinutes:     1.minute,
      # SoftwareUpdateInstallationPercentComplete: 1.minute,
      # SoftwareUpdateScheduledStartTime:          1.minute,
      # SoftwareUpdateVersion:                     1.minute,
      # TpmsHardWarnings:                          1.minute,
      # TpmsSoftWarnings:                          1.minute,
      # ValetModeEnabled:                          1.minute,
      # WheelType:                                 30.minutes,
      # WiperHeatEnabled:                          30.minutes,
      # LocatedAtHome:                             30.minutes,
      # LocatedAtWork:                             30.minutes,
      # LocatedAtFavorite:                         30.minutes,
      # SettingDistanceUnit:                       30.minutes,
      # SettingTemperatureUnit:                    30.minutes,
      # Setting24HourTime:                         30.minutes,
      # SettingTirePressureUnit:                   30.minutes,
      # SettingChargeUnit:                         30.minutes,
      # ClimateSeatCoolingFrontLeft:               30.minutes,
      # ClimateSeatCoolingFrontRight:              30.minutes,
    }.to_h { |k, v| [k, { interval_seconds: v }] }
  end
end
