# The single source of truth for the spending-category vocabulary AND for which
# merchant belongs to which category.
#
# It used to live in four places that had to be edited together — this module,
# Jil task 453's merchant rules, the `choices` on the categorization Prompt,
# and CustomChart 4's color map. Adding a category meant remembering all four,
# and `Extra Expense` is in the data exactly once because someone did not.
#
# Now Rails owns it and everything else derives: Jil reads it through
# `TransactionCategory.all()` / `.colors()` / `.match()` (see
# Jil::Methods::TransactionCategory) so the tasks no longer carry a copy, and
# the chart's color map is generated from `chart_color_config` rather than
# maintained alongside it.
# rubocop:disable Metrics/ModuleLength -- almost all of it is MERCHANT_RULES, a
# 288-entry data table with one merchant per line. Splitting it out to satisfy a
# length budget would put the vocabulary in one file and the rules in another,
# which is the several-places-to-edit problem this module was made to end.
module TransactionCategory
  # ONE hash: the category and the color it is drawn in. The list and the
  # palette are the same thing, so keeping them as separate constants meant
  # writing all 22 names twice and having no way to notice when they drifted.
  #
  # Alphabetical, and `ALL` re-sorts rather than trusting this to stay that
  # way — adding one in the wrong place should not reorder the UI.
  CATEGORIES = {
    alcohol:        "#CBB994",
    car:            "#8A6D3B",
    "card payment": "#6E7681",
    "eat out":      "#D95926",
    fun:            "#F5D67B",
    groceries:      "#3987E5",
    health:         "#59C26A",
    hobby:          "#45B6D4",
    home:           "#C98500",
    hosting:        "#A8E6CF",
    insurance:      "#DCA3B1",
    medical:        "#1DC91D",
    mortgage:       "#E66767",
    other:          "#AEB6C2",
    "pay check":    "#008300",
    people:         "#14C8B4",
    pets:           "#B07CC6",
    shopping:       "#D55181",
    subscriptions:  "#9085E9",
    taxes:          "#C91DC9",
    travel:         "#9EC91D",
    utilities:      "#199E70",
  }.freeze

  ALL = CATEGORIES.keys.sort_by(&:to_s).freeze
  DEFAULT = :other

  # Which merchant means which category. Ported verbatim from Jil task 453,
  # which owned it until 2026-08-12 and is now deleted — a copy in Jil and a
  # copy here is the exact problem this module exists to end.
  #
  # ORDER IS LOAD-BEARING. The first rule that matches wins, so the specific
  # must precede the general: "AMAZON WEB" is hosting and has to be tested
  # before "AMAZON" claims it for shopping, and "PRIME PMTS"/"PRIME VIDEO" are
  # subscriptions before "AMZN" sees them. Re-sorting this hash silently
  # recategorizes spending.
  #
  # Fragments rather than one long pattern per category, purely so a merchant
  # can be added as a single word on its own line. They are joined with `|`
  # into exactly the alternation Jil held as one string.
  #
  # Note the anchored ones (`\A...\z`): "JPMORGAN CHASE" alone is the mortgage,
  # but as a substring it would also swallow every other Chase line item.
  MERCHANT_RULES = {
    mortgage:       ["\\AJPMORGAN CHASE\\z"],
    "pay check":    ["direct deposit", "check deposit"],
    "card payment": ["\\ACHASE CREDIT CRD\\z", "\\APayment\\z"],
    insurance:      [
      "PROG DIRECT",
      "BEAR RIVER MUT",
      "INSUR",
      "GEICO",
      "STATE FARM",
      "ALLSTATE",
      "TRAVELERS",
      "CLAIM SOLUTI",
    ],
    taxes:          ["\\AIRS\\z", "INTUIT", "UDOT RUC", "TREASURY", "UTAH. MVED"],
    hosting:        ["DIGITALOCEAN", "AMAZON WEB", "TWILIO", "NAME.?CHEAP", "GITHUB"],
    subscriptions:  [
      "NETFLIX",
      "DISNEY",
      "SPOTIFY",
      "CRUNCHYROLL",
      "OPENAI",
      "CLAUDE.AI",
      "ANTHROPIC",
      "KINDLE",
      "PRIME PMTS",
      "PRIME VIDEO",
      "HULU",
      "PATREON",
      "DOLLARSHAVECLUB",
    ],
    groceries:      [
      "COSTCO",
      "HARMONS",
      "TRADER JOE",
      "SMITHS",
      "TARGET",
      "WAL.?MART",
      "WM SUPERCENTER",
      "SPROUTS",
      "WINCO",
      "QFC",
      "STOKES",
      "FRESH MARKET",
      "CHINATOWN SUPERMARK",
      "OCEAN MART",
      "PIRATE O",
    ],
    alcohol:        [
      "LIQUOR",
      "BREWING",
      "BREWERY",
      "BREWI",
      "WHISKEY",
      "SALOON",
      "HELPER BEER",
      "LUCKY 13",
      "STATION BAR",
    ],
    "eat out":      [
      "GOLD FISH",
      "LOS TORITOS",
      "ICHI JAPAN",
      "TORO RAMEN",
      "TEXAS ROADHOUSE",
      "IN.N.OUT",
      "CAFE RIO",
      "CHICK.FIL.A",
      "KNEADERS",
      "PEPPER LUNCH",
      "GURAS",
      "ROXBERRY",
      "TROPICAL SMOOTHIE",
      "QUENCH",
      "SLACKWATER",
      "SWIG",
      "CHIPOTLE",
      "PANDA EXPRESS",
      "MCDONALD",
      "WENDY",
      "SUBWAY",
      "STARBUCKS",
      "DOMINO",
      "PIZZA",
      "SUSHI",
      "RAMEN",
      "BAKERY",
      "GRILL",
      "TACO",
      "BURGER",
      "CAFE",
      "DINER",
      "BISTRO",
      "RESTAURANT",
      "BERTOS",
      "BETOS",
      "DOORDASH",
      "GRUBHUB",
      "UBER . EATS",
      "DUTCH BROS",
      "BEANS .{0,6}BREWS",
      "HANDELS",
      "HUMAN BEAN",
      "THB ",
      "HAMACHI",
      "OLIVE GARDEN",
      "FIVE GUYS",
      "KFC",
      "IHOP",
      "SBARRO",
      "POTBELLY",
      "DAIRY QUEEN",
      "FREDDYS",
      "SHAKE SHACK",
      "WAFFLE LOVE",
      "NEKTER",
      "ACAI",
      "THIRST DRINKS",
      "SUPER CHIX",
      "KIN KAO",
      "PHO ",
      "RED FORT",
      "SAFFRON VALLEY",
      "UMAMI",
      "VIETOPIA",
      "ASIAN CITY",
      "TERIYAKI",
      "NOODLE",
      "KABOB",
      "KIPOS",
      "MARMALADE",
      "LA FOUNTAIN",
      "JIMS -",
      "SKINNYFATS",
      "THE PIE",
      "CRAB POT",
      "HOUSTON.S HOT",
      "COFFEE",
      "CANNOLI",
      "JUICE",
    ],
    utilities:      [
      "ROCKYMTN",
      "DOMINION ENERGY",
      "HERRIMAN CITY",
      "JORDAN BASIN",
      "T.MOBILE",
      "LUMEN",
      "CENTURYLINK",
      "XFINITY",
      "COMCAST",
      "WASATCH FRONT",
      "QUANTUM FIBER",
      "ENBRIDGE",
      "RIVERTON CITY",
      "TRANS JORDAN",
      "SOUTH VALLEY SEW",
    ],
    home:           [
      "HOME DEPOT",
      "LOWE",
      "IKEA",
      "RC WILLEY",
      "ACE HARDWARE",
      "MENARDS",
      "SMARTWINGS",
      "CRATE AND BARREL",
      "ASHLEYFURNITURE",
      "AT HOME STORE",
      "HOMEGOODS",
      "RUGGABLE",
      "MILKHOUSE CANDLE",
      "PEST CONTR",
      "VIVINT",
      "INOVELLI",
      "DR. VOLTS",
    ],
    car:            [
      "TESLA",
      "QUICKQUACK",
      "MCNEILS",
      "DMV",
      "NISSAN",
      "JIFFY LUBE",
      "CHEVRON",
      "MAVERIK",
      "SINCLAIR",
      "AUTOZONE",
      "LES SCHWAB",
      "LYFT",
      "UBER .TRIP",
      "UBR.",
      "BIG O",
      "O.REILLY",
      "PARKING",
      "PARKWHIZ",
      "CYCLE GEAR",
    ],
    pets:           [
      "PETSMART",
      "PETCO",
      "CHEWY",
      "VETERI",
      "GENTLE VET",
      "ROVER.COM",
      "ANIMAL HOSPITAL",
    ],
    health:         ["SERENITY MENTAL", "MOUNTAIN YOGA", "YOGA BARN", "HAPPINESS WITHIN"],
    medical:        [
      "PHARMACY",
      "WALGREENS",
      "CVS",
      "DENTAL",
      "DDS",
      "ORTHODONT",
      "CLINIC",
      "MEDICAL",
      "HOSPITAL",
      "OPTOMETRY",
      "RETINA",
      "VITREOUS",
      "INTERMOUNTAIN HE",
      "ORTHOFEET",
    ],
    hobby:          [
      "GAME HAVEN",
      "GALAXYOFGAMES",
      "HOBBY LOBBY",
      "MICHAELS",
      "JOANN",
      "GAMESTOP",
      "THIEVES GUILD",
      "NINTENDO",
      "STEAM",
      "BOARDGAMES",
      "OASIS GAMES",
      "RECORD SHO",
      "LEGENDARIUM",
    ],
    travel:         [
      "AIRBNB",
      "RESORT",
      "LODGE",
      "HOTEL",
      "MARRIOTT",
      "HILTON",
      "DELTA AIR",
      "EXPEDIA",
      "FRONTIER RESERV",
      "WSFERRIES",
      "CITY PASS",
      "HUDSONNEWS",
      "STRAWBERRY BAY",
    ],
    fun:            [
      "MOMENTUM",
      "CINEMA",
      "THEATRE",
      "THEATER",
      "MEGAPLEX",
      "TRAMPOLINE",
      "BOWLING",
      "TOPGOLF",
      "FAT CATS",
      "FIESTA FUN",
      "MUSEUM",
      "NHMU",
      "DLR ",
      "DELTA CENTER",
      "THEAT",
      "FANDANGO",
      "GARDNER VILLAGE",
      "STATE PARKS",
      "HUNT.FISH",
    ],
    people:         ["\\AVENMO\\z", "ZELLE", "CASH APP", "PAYPAL"],
    shopping:       [
      "AMAZON",
      "AMZN",
      "T.J. MAXX",
      "TJ MAXX",
      "ROSS STORES",
      "KOHL",
      "BEST ?BUY",
      "WAYFAIR",
      "ETSY",
      "EBAY",
      "SCHEELS",
      "REI #",
      "SIERRA #",
      "AMERICAN EAGLE",
      "FAMOUS FOOTWEAR",
      "BARNES",
      "MICROSOFT",
      "FABLETICS",
      "OWALA",
      "SPORTSMAN",
      "SPORTING GOODS",
      "UPS STORE",
      "JEWELR",
    ],
  }.freeze

  # Compiled once. IGNORECASE and MULTILINE because that is exactly what Jil's
  # `to_regex` applied — without IGNORECASE the lowercase "direct deposit" rule
  # would stop matching, and the port would silently lose pay checks.
  MERCHANT_PATTERNS = MERCHANT_RULES.transform_values { |fragments|
    ::Regexp.new(fragments.join("|"), ::Regexp::IGNORECASE | ::Regexp::MULTILINE)
  }.freeze

  # What was BOUGHT, for merchants that sell everything. The merchant rules put
  # every Amazon charge under `shopping`, which is true of the shop and useless
  # about the purchase.
  #
  # `shopping` is treated as a failure, not a bucket. It says only "a shop sold
  # it", which is true of everything and useful about nothing, so these rules
  # reach hard and the residue should be tiny.
  #
  # ORDER IS THE DESIGN. First match wins, and several of these deliberately
  # overlap:
  #
  #   * a CORD is home, a CABLE or WIRE is hobby. Read literally, as asked —
  #     an extension cord powers the house, a USB cable is workbench kit. So
  #     `hobby` is tested before `home`, and something naming both (a "Cord
  #     Organizer Magnetic Cable Clip") lands in hobby.
  #   * GAMES are fun, but dice, TCG, Lorcana and Warhammer are hobby. `hobby`
  #     first keeps tabletop out of the generic games bucket.
  #   * `home` is LAST of the specific rules because it is the widest. A
  #     "camping lantern" is fun before `lantern` can make it home.
  #
  # `medical` covers hygiene as well as medicine — toothpaste and tampons sit
  # with the ibuprofen. Note `pads` is never used bare: mouse pads, brake pads
  # and sticky-note pads would all be swept up.
  ITEM_RULES = {
    pets:      [
      "\\bdog\\b",
      "\\bdogs\\b",
      "\\bcat\\b",
      "\\bcats\\b",
      "\\bpet\\b",
      "\\bpets\\b",
      "\\bpuppy\\b",
      "\\bkitten\\b",
      "\\bfeline\\b",
      "\\bcanine\\b",
      "litter box",
      "cat litter",
      "pee pads",
      "\\bleash\\b",
      "pet carrier",
      "\\bcollar\\b",
      "\\bkennel\\b",
      "\\bcrate\\b.{0,12}\\bpet",
      "chew toy",
      "\\bcatnip\\b",
      "\\bharness\\b",
      "bird seed",
      "\\bwoof\\b",
      "natural balance",
      "blue buffalo",
      "\\bhabitat\\b",
      "midwest homes",
      "\\btreats?\\b",
      "\\bpupsicle\\b",
      "\\bforager\\b",
      "\\bterrarium\\b",
      "\\baquarium\\b",
    ],
    medical:   [
      # Medicine
      "pedialyte",
      "pepto",
      "ibuprofen",
      "acetaminophen",
      "tylenol",
      "advil",
      "\\bgauze\\b",
      "first aid",
      "\\bbandage",
      "band.aid",
      "antacid",
      "cough drop",
      "\\bantibiotic",
      "\\bvitamin",
      "\\bsupplement",
      "blood pressure", # `pillbox` is deliberately absent: "Pillbox Games" is a board game
      # publisher, and "pill organizer" already covers the real thing.
      "pill organizer",
      "\\bmedicine\\b",
      "\\bmedication",
      "\\bprescription\\b",
      "\\bantiseptic\\b",
      "\\bibuprof",
      # Hygiene
      "toothbrush",
      "toothpaste",
      "\\bfloss\\b",
      "mouthwash",
      "\\btampon",
      "menstrual",
      "sanitary pad",
      "\\bpanty liner",
      "\\brazor\\b",
      "\\bdeodorant\\b",
      "antiperspirant",
      "\\bshampoo\\b",
      "conditioner\\b",
      "body wash",
      "\\bsunscreen\\b",
      "\\bnail clipper",
      "\\bear plug",
      "\\bthermometer\\b",
      "\\bheating pad\\b",
      "\\bcompression sleeve\\b",
      "\\bbenadryl\\b",
      "\\bbiotene\\b",
      "\\blozenge",
      "\\bvaseline\\b",
      "lip balm",
      "body scrub",
      "body powder",
      "castor oil",
      "\\bcolgate\\b",
      "\\bgarnier\\b",
      "exam gloves",
      "nitrile",
      "water flosser",
      "\\bflosser\\b",
      "eyelash",
      "\\bhair tie",
      "hair pick",
      "\\bcomb\\b",
      "eyeglass",
      "blue light block",
      "\\bcream\\b",
      "\\bointment\\b",
      "\\bimmunity\\b",
      "\\bedp\\b",
      "\\bcologne\\b",
      "\\bperfume\\b",
      "eau de",
      "resistance loop",
      "exercise band",
      "\\btreadmill\\b",
      "walking pad",
    ],
    groceries: [
      "celsius",
      "hint water",
      "\\bpropel\\b",
      "gatorade",
      "sprite",
      "coca.cola",
      "\\bpopcorn\\b",
      "protein shake",
      "protein powder",
      "\\bsyrup\\b",
      "grenadine",
      "olive oil",
      "\\bseasoning\\b",
      "\\bsnack",
      "granola",
      "\\bcereal\\b",
      "\\bcandy\\b",
      "\\bchocolate\\b",
      "beef jerky",
      "coffee beans",
      "ground coffee",
      "k.cups?\\b",
      "\\btea bags\\b",
      "electrolyte",
      "drink mix",
      "sparkling water",
      "energy drink",
      "\\bgum\\b",
      "\\bmints?\\b",
      "\\bpeanuts?\\b",
      "\\balmonds?\\b",
      "\\bsoda\\b",
      "\\bjuice\\b",
      "\\bsauce\\b",
      "\\bspice\\b",
      "spring water",
      "bottled water",
      "\\bcinnamon\\b",
      "food coloring",
      "\\braspberr",
      "\\bgrinder set\\b",
      "\\bmccormick\\b",
      "\\bolive\\b",
      "\\bgarlic\\b",
    ],
    car:       [
      "\\btesla\\b",
      "model [3y]\\b",
      "\\bwindshield\\b",
      "\\bwiper blade",
      "\\btire\\b",
      "\\btires\\b",
      "motor oil",
      "\\bautomotive\\b",
      "license plate",
      "\\bobd2?\\b",
      "\\bdash ?cam\\b",
      "\\bmotorcycle\\b",
      "\\bhelmet\\b",
      "turn signal",
      "\\bheadlight\\b",
      "car door",
      "\\bcup holder\\b",
    ],
    travel:    [
      "\\bluggage\\b",
      "\\bsuitcase\\b",
      "packing cubes",
      "travel pillow",
      "passport",
      "\\bcarry.on\\b",
    ],
    hobby:     [
      # Tabletop, before `games` can claim it for fun
      "\\bdice\\b",
      "\\bdnd\\b",
      "dungeons.{1,5}dragons",
      "\\btcg\\b",
      "card sleeves",
      "board game",
      "lorcana",
      "magic the gathering",
      "\\bwarhammer\\b",
      "\\bminiatures?\\b",
      "\\bjigsaw\\b",
      # Wires, cables, tools
      "\\bcable",
      "\\bwire",
      "\\btool\\b",
      "\\btools\\b",
      "\\bpliers\\b",
      "screwdriver",
      "\\bwrench\\b",
      "\\bdrill\\b",
      "\\bsolder",
      "multimeter",
      "\\bclamp",
      "\\bcaliper",
      "\\bhex key",
      "\\ballen\\b",
      "\\bvise\\b",
      "\\bconnector",
      "\\badapter\\b",
      "\\busb\\b",
      "\\bhdmi\\b",
      "\\bethernet\\b",
      "\\bsoldering\\b",
      "heat shrink",
      "\\bterminal block",
      # Tinkering and making
      "3d printer",
      "printer filament",
      "\\bfilament\\b",
      "\\bresin\\b",
      "development board",
      "\\barduino\\b",
      "raspberry pi",
      "\\besp32",
      "\\bbreadboard\\b",
      "\\bmicrocontroller",
      "\\bcraft",
      "\\bsewing\\b",
      "\\byarn\\b",
      "\\bpaint brush",
      "\\bmarkers?\\b",
      "\\bjournal\\b",
      "\\bnotebook\\b",
      "\\bsketch",
      "\\bcamera\\b",
      "\\blens\\b",
      "\\btripod\\b",
      "\\bbattery charger\\b",
      # Tabletop and cards
      "\\bmeeples?\\b",
      "\\bchess\\b",
      "\\bmtg\\b",
      "deck box",
      "card deck",
      "trading card",
      "playing cards",
      "\\bbookmark",
      "letter tiles",
      "pirate coins",
      "\\bdivided tray\\b",
      # Electronics and tech
      "\\btablet\\b",
      "\\bmonitor\\b",
      "\\bkeyboard\\b",
      "\\btrackpad\\b",
      "\\bcharger\\b",
      "\\bbatteries\\b",
      "\\bbattery\\b",
      "screen protector",
      "\\bstream deck\\b",
      "\\blabel printer\\b",
      "\\bwriting tablet\\b",
      "docking station",
      "smart plug",
      "\\bwifi\\b",
      "\\bmesh system\\b",
      "\\bsensor\\b",
      "\\bpcb\\b",
      "\\bhotend\\b",
      "\\bender 3\\b",
      "project case",
      "\\bswitch 2 pin\\b",
      "\\bmodule\\b",
      "\\bphone mount\\b",
      "\\bphone case\\b",
      "\\bmagic \\w+pad\\b",
      # Stationery, craft, making
      "super glue",
      "\\badhesive\\b",
      "\\bnotepad\\b",
      "sticky notes",
      "binder clips",
      "bulldog clips",
      "file folders",
      "dry erase",
      "\\bwhiteboard\\b",
      "memo board",
      "\\bpencils?\\b",
      "\\bpens?\\b",
      "paper cutter",
      "paper trimmer",
      "sign holder",
      "magnifying glass",
      "\\bruler\\b",
      "sanding",
      "\\bairbrush\\b",
      "\\bcrucible\\b",
      "\\bfoundry\\b",
      "plasti dip",
      "\\bbeads\\b",
      "\\bfunnels?\\b",
      "learning counters",
      "centimeter cubes",
      "\\bflashlight",
      "\\btv box\\b",
      "\\bmousepad\\b",
      "mouse pad",
      "voice recording",
      "\\busb.?c\\b",
      "\\buhd\\b",
      "\\b4k\\b",
      "full hd",
      "for iphone",
      "cell phone",
      "\\bnails\\b",
      "\\bbooks?\\b",
      "wood chips",
    ],
    fun:       [
      # Gaming
      "nintendo switch",
      "\\bjoy.?con",
      "\\bjoystick\\b",
      "\\bcontroller",
      "\\bxbox\\b",
      "playstation",
      "\\bps5\\b",
      "gaming mouse",
      "gaming keyboard",
      "\\bamiibo\\b",
      "\\bgame\\b",
      "\\bgames\\b",
      "\\bgaming\\b",
      "\\btoy\\b",
      "\\btoys\\b",
      "\\bpuzzle\\b",
      "\\bplush\\b",
      "\\bfidget\\b",
      "\\blego\\b",
      # Outdoors
      "\\bcamping\\b",
      "\\bcamp\\b",
      "\\btents?\\b",
      "sleeping bag",
      "\\bhammocks?\\b",
      "\\bhiking\\b",
      "\\btrekking\\b",
      "\\bcooler\\b",
      "\\bkayak",
      "paddle board",
      "life jacket",
      "\\bfishing\\b",
      "\\bbinoculars\\b",
      "\\blantern\\b",
      "\\bcanteen\\b",
      # Dressing up and knick-knacks
      "sunglasses",
      "\\bcostume",
      "\\bhalloween\\b",
      "\\bcrystals?\\b",
      "\\bgemstone",
      "\\bgeode\\b",
      "worry stone",
      # Bottles and jars
      "\\bbottles?\\b",
      "\\bjars?\\b",
      "\\bflask\\b",
      "\\btumbler\\b",
      "\\bthermos\\b",
      "\\bcanteen\\b",
      # Dress-up, props, collectibles
      "\\bsword\\b",
      "\\bcloak\\b",
      "\\brobe\\b",
      "\\bcape\\b",
      "\\bknight\\b",
      "\\bmedieval\\b",
      "renaissance",
      "\\bski mask\\b",
      "\\bdecals\\b",
      "\\bsquishies\\b",
      "\\btamagotchi\\b",
      "stuffed animal",
      "\\bplushie\\b",
      "remote control",
      "\\bglow in\\b",
      "\\bluminous\\b",
      "\\bjingle bells\\b",
      # Screen and tabletop entertainment
      "\\bblu.ray\\b",
      "\\bdvd\\b",
      "film collection",
      "\\bbandai\\b",
      # Outdoors continued
      "\\bbushcraft\\b",
      "\\bforaging\\b",
      "dry bag",
      "tactical backpack",
      "\\bwagon\\b",
      "\\bsnorkel\\b",
      "\\btactical\\b",
      "shell buttons",
      "extremerate",
      "\\bowala\\b",
      "emotional support",
    ],
    home:      [
      # Fixtures and systems
      "light bulb",
      "\\bbulbs?\\b",
      "light socket",
      "\\bthermostat",
      "\\bfaucet\\b",
      "\\bcaulk\\b",
      "weather ?strip",
      "smoke detector",
      "\\bdoorbell\\b",
      "outlet cover",
      "\\bdrywall\\b",
      "\\bgrout\\b",
      "\\bshowerhead\\b",
      "air filter",
      "furnace filter",
      "\\bcircuit breaker",
      "\\blamp\\b",
      "\\bcord\\b",
      "power strip",
      "extension cord",
      "\\boutlet\\b",
      "\\bswitch plate",
      "\\bfans?\\b",
      "\\bhumidifier\\b",
      # Soft furnishings
      "\\bcurtain",
      "\\bblinds?\\b",
      "\\bshades?\\b",
      "\\brug\\b",
      "\\brugs\\b",
      "\\bmat\\b",
      "\\bmats\\b",
      "\\btowels?\\b",
      "\\bblanket",
      "\\bpillow",
      "\\bbedding\\b",
      "\\bsheets? set",
      "\\bduvet\\b",
      "\\bcomforter\\b",
      "\\bthrow\\b",
      # Kitchen and dining
      "\\bsilverware\\b",
      "\\bcutlery\\b",
      "\\butensils?\\b",
      "\\bforks?\\b",
      "\\bspoons?\\b",
      "\\bplates?\\b",
      "\\bbowls?\\b",
      "\\bdish",
      "\\bmugs?\\b",
      "\\bglassware\\b",
      "dinnerware",
      "\\bcookware\\b",
      "\\bskillet\\b",
      "\\bsaucepan\\b",
      "\\bstockpot\\b",
      "\\bkitchen",
      "\\bcolander\\b",
      "\\bspatula\\b",
      "\\bstraws?\\b",
      "\\bdispenser\\b",
      "parchment paper",
      "\\bfood storage\\b",
      "\\bairfryer\\b",
      "air fryer",
      # Storage, furniture, decor
      "storage bin",
      "\\borganizer\\b",
      "\\bshelf\\b",
      "\\bshelves\\b",
      "\\brack\\b",
      "\\bhooks?\\b",
      "\\bhangers?\\b",
      "\\bfurniture\\b",
      "\\bdesk\\b",
      "\\bchair\\b",
      "\\btable\\b",
      "\\bstool\\b",
      "\\bdecor",
      "\\bwall art\\b",
      "\\bpicture frame",
      "\\bvase\\b",
      "\\bcandle",
      "\\bclock\\b",
      "\\bmirror\\b",
      "book ends",
      "\\bbookend",
      # Cleaning and laundry
      "\\bdetergent\\b",
      "\\blaundry\\b",
      "\\bhamper\\b",
      "\\bbroom\\b",
      "\\bmop\\b",
      "\\bvacuum\\b",
      "\\bcleaner\\b",
      "\\bcleaning\\b",
      "disinfect",
      "\\bwipes\\b",
      "\\btrash\\b",
      "\\bgarbage\\b",
      "\\bstain remover\\b",
      "\\bsoap dispenser\\b",
      "shower curtain",
      "\\btoilet\\b",
      "\\bplunger\\b",
      # Kitchen continued
      "\\bknife holder\\b",
      "\\bgrill\\b",
      "\\bgriddle\\b",
      "\\bpan\\b",
      "\\bwhisk\\b",
      "\\bchopsticks\\b",
      "heat diffuser",
      "meal prep",
      "\\bcontainers?\\b",
      "\\bice maker\\b",
      "\\bcups?\\b",
      "\\bsyphon\\b",
      "\\btablecloth\\b",
      "\\bcutting board\\b",
      # Fixtures continued
      "\\bdimmer\\b",
      "motion sensor",
      "occupancy sensor",
      "ceiling fan",
      "light fixture",
      "\\bwall mount\\b",
      "\\btv stand\\b",
      "\\bbidet\\b",
      "\\bsprinkler\\b",
      "water filter",
      "\\bradio\\b",
      # Storage, furniture, decor continued
      "\\bcabinet\\b",
      "\\bdrawer",
      "\\btension rod\\b",
      "\\bbacksplash\\b",
      "\\bshower caddy\\b",
      "under sink",
      "\\bhanging basket\\b",
      "\\bwatering can\\b",
      "\\bstair tread",
      "\\bfencing\\b",
      "\\borchid\\b",
      "\\bplanter\\b",
      "\\bincense\\b",
      "\\blanterns?\\b",
      "\\bbells\\b",
      "\\bsign\\b",
      "\\btrunk\\b",
      "\\bbaskets?\\b",
      "\\bbed\\b",
      "\\bchairs\\b",
      "\\bstorage\\b",
      # Pest and yard
      "mouse trap",
      "\\bpest\\b",
      "\\bvole",
      "bug.a.salt",
      "\\bfly edition\\b",
      "peel and stick",
      "\\bbissell\\b",
      "\\bfarberware\\b",
      "\\brubbermaid\\b",
      "houseware",
      "\\bshaker\\b",
      "\\bbartender\\b",
      "lunch bag",
      "light display",
      "\\bdrinking\\b",
    ],
  }.freeze

  ITEM_PATTERNS = ITEM_RULES.transform_values { |fragments|
    ::Regexp.new(fragments.join("|"), ::Regexp::IGNORECASE | ::Regexp::MULTILINE)
  }.freeze
  # Strays render in a neutral gray rather than borrowing a real category's
  # color, so "this is not a real category" is visible on the chart.
  FALLBACK_COLOR = "#475569".freeze

  class << self
    # Stored lowercase ("eat out"); rendered titleized ("Eat Out"). The select
    # submits the stored form so nothing round-trips into a new spelling.
    def options
      ALL.map { |category| [category.to_s.titleize, category.to_s] }
    end

    def label(category)
      category.to_s.titleize
    end

    def color(category)
      CATEGORIES[category.to_s.to_sym] || FALLBACK_COLOR
    end

    def valid?(category)
      CATEGORIES.key?(category.to_s.to_sym)
    end

    # Nil rather than DEFAULT on an unknown value: silently rewriting an
    # unrecognized category to "other" would erase the fact that something
    # wrote a category nothing knows about. `Extra Expense` is in the data
    # exactly once for that reason.
    def cast(category)
      ALL.detect { |known| known.to_s == category.to_s }
    end

    # Which category a merchant name belongs to, or nil when no rule claims it.
    #
    # NIL, not DEFAULT. Jil returned "other" for anything unmatched, which is
    # right when a human is about to see the answer in a prompt they can
    # correct — and wrong when it is applied to thousands of rows unattended,
    # where it would bury every merchant nobody has written a rule for under a
    # category that looks deliberate. Callers that want the old behaviour say
    # so; see Jil::Methods::TransactionCategory#match.
    def for_merchant(merchant)
      text = merchant.to_s
      return nil if text.blank?

      # `detect` on an ordered hash — first match wins, which is the whole
      # contract MERCHANT_RULES' ordering encodes.
      MERCHANT_PATTERNS.detect { |_category, pattern| pattern.match?(text) }&.first
    end

    # What a purchase was, from the item description — for merchants that sell
    # everything and whose own name says nothing useful.
    #
    # Nil when no rule is confident, and nil MEANS "leave it where the merchant
    # put it". That is the whole safety property: an unrecognized item stays
    # `shopping` rather than being pulled somewhere worse.
    def for_item(text)
      body = text.to_s
      return nil if body.blank?

      ITEM_PATTERNS.detect { |_category, pattern| pattern.match?(body) }&.first
    end

    # The color map in the exact shape CustomChart 4's config expects, so the
    # chart is GENERATED from this rather than kept in step with it by hand.
    def chart_color_config
      ALL.map { |category| "#{category} = #{CATEGORIES[category]}" }.join("\n")
    end

    # Categories present in the data but outside the vocabulary. These render
    # uncolored on the chart and are what the banking page's cleanup surface
    # exists to catch.
    #
    # Reads bank_transactions, which is where a category is stored now. The
    # events it used to read still carry a mirrored copy, but only for the
    # fraction of transactions an alert email ever covered.
    def unknown_in_use
      used = ::BankTransaction.distinct.pluck(:category)
      used.compact_blank.reject { |category| valid?(category) }
    end
  end
end
# rubocop:enable Metrics/ModuleLength
