source "https://rubygems.org"

gem "rails", "7.0"
gem "pg"
# gem "therubyracer"
gem "sprockets", "~>3.0"
gem "coffee-rails"
gem "sass-rails"
gem "uglifier", ">= 1.3.0"
gem "jquery-rails"
gem "jquery-ui-rails"
gem "jbuilder", "~> 2.0"
gem "bootsnap"
gem "jsbundling-rails"

gem "sprockets-rails"
gem "dotenv-rails"
gem "puma"
gem "redis"
gem "redis-namespace"
gem "sidekiq"
gem "sidekiq-cron"
gem "json", "~> 2.3"
gem "autoprefixer-rails"
gem "font-awesome-rails"
gem "colorize"
gem "faker"
gem "twilio-ruby", "~> 4.11.1"
gem "sinatra", :require => nil
gem "gmaps4rails"
gem "underscore-rails"
gem "httparty"
gem "touchpunch-rails"

gem "bcrypt"
gem "rails_autolink"
gem "exception_notification"
gem "slack-notifier"
gem "nokogiri", "~> 1.10.4"
gem "capybara"
gem "poltergeist"
gem "launchy"
gem "numbers_in_words"
gem "kaminari"
gem "rest-client"
gem "oily_png"
gem "chroma"
gem "inline_svg"
gem "ice_cube"
gem "webpush"
gem "chronic"
gem "aws-sdk-s3"
gem "erubis"

# gem "command_proposal", path: "../command_proposal"
gem "command_proposal", git: "https://github.com/Rockster160/command_proposal.git"
# gem "command_proposal", "1.0.19"

group :development, :test do
  gem "spring"
  gem "annotate"
  gem "listen"
  gem "rails_real_favicon"
  gem "pry-rails"
  gem "pry-byebug"
  gem "spring-commands-rspec"
  gem "rspec-rails"
  gem "better_errors"
  gem "simplecov", :require => false, :group => :test
end
