Time::DATE_FORMATS[:short] = "%-m/%-d/%y"
Time::DATE_FORMATS[:short_with_time] = "%-m/%-d/%y %H:%M:%S"
Time::DATE_FORMATS[:simple] = "%b %-d, %Y"
Time::DATE_FORMATS[:simple_with_time] = "%b %-d, %Y %H:%M"
Time::DATE_FORMATS[:simple12_with_time] = "%b %-d, '%y %-l:%M%P"
Time::DATE_FORMATS[:time_with_simple12] = "%-l:%M %P %b %-d, '%y"
Time::DATE_FORMATS[:short_weekday_with_date] = "%a %b %-d, %Y %H:%M"
Time::DATE_FORMATS[:short_day_month] = "%-d %b"
